"""
This type stub file was generated by pyright.
"""

import typing
from .filters import AbstractFilter
from ..handler import Handler

class FiltersFactory:
    """
    Filters factory
    """
    def __init__(self, dispatcher) -> None:
        ...
    
    def bind(self, callback: typing.Union[typing.Callable, AbstractFilter], validator: typing.Optional[typing.Callable] = ..., event_handlers: typing.Optional[typing.List[Handler]] = ..., exclude_event_handlers: typing.Optional[typing.Iterable[Handler]] = ...): # -> None:
        """
        Register filter

        :param callback: callable or subclass of :obj:`AbstractFilter`
        :param validator: custom validator.
        :param event_handlers: list of instances of :obj:`Handler`
        :param exclude_event_handlers: list of excluded event handlers (:obj:`Handler`)
        """
        ...
    
    def unbind(self, callback: typing.Union[typing.Callable, AbstractFilter]): # -> None:
        """
        Unregister filter

        :param callback: callable of subclass of :obj:`AbstractFilter`
        """
        ...
    
    def resolve(self, event_handler, *custom_filters, **full_config) -> typing.List[typing.Union[typing.Callable, AbstractFilter]]:
        """
        Resolve filters to filters-set

        :param event_handler:
        :param custom_filters:
        :param full_config:
        :return:
        """
        ...
    


