"""
This type stub file was generated by pyright.
"""

from typing import Optional

class State:
    """
    State object
    """
    def __init__(self, state: Optional[str] = ..., group_name: Optional[str] = ...) -> None:
        ...
    
    @property
    def group(self): # -> Type[StatesGroup]:
        ...
    
    def get_root(self): # -> Type[StatesGroup]:
        ...
    
    @property
    def state(self): # -> str | None:
        ...
    
    def set_parent(self, group): # -> None:
        ...
    
    def __set_name__(self, owner, name): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...
    async def set(self): # -> None:
        ...
    


class StatesGroupMeta(type):
    def __new__(mcs, name, bases, namespace, **kwargs): # -> Self@StatesGroupMeta:
        ...
    
    @property
    def __group_name__(cls) -> str:
        ...
    
    @property
    def __full_group_name__(cls) -> str:
        ...
    
    @property
    def states(cls) -> tuple:
        ...
    
    @property
    def childs(cls) -> tuple:
        ...
    
    @property
    def all_childs(cls): # -> tuple[Unknown, ...]:
        ...
    
    @property
    def all_states(cls): # -> tuple[Unknown, ...]:
        ...
    
    @property
    def all_states_names(cls): # -> tuple[Unknown, ...]:
        ...
    
    @property
    def states_names(cls) -> tuple:
        ...
    
    def get_root(cls): # -> Self@StatesGroupMeta:
        ...
    
    def __contains__(cls, item): # -> bool:
        ...
    
    def __str__(self) -> str:
        ...
    


class StatesGroup(metaclass=StatesGroupMeta):
    @classmethod
    async def next(cls) -> str:
        ...
    
    @classmethod
    async def previous(cls) -> str:
        ...
    
    @classmethod
    async def first(cls) -> str:
        ...
    
    @classmethod
    async def last(cls) -> str:
        ...
    


default_state = ...
any_state = ...
