"""
This type stub file was generated by pyright.
"""

from typing import Type, TypeVar

__all__ = ('DataMixin', 'ContextInstanceMixin')
class DataMixin:
    @property
    def data(self): # -> Any | dict[Unknown, Unknown]:
        ...
    
    def __getitem__(self, item): # -> Any:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def __delitem__(self, key): # -> None:
        ...
    
    def __contains__(self, key): # -> bool:
        ...
    
    def get(self, key, default=...): # -> Any | None:
        ...
    


T = TypeVar('T')
class ContextInstanceMixin:
    def __init_subclass__(cls, **kwargs): # -> Type[Self@ContextInstanceMixin]:
        ...
    
    @classmethod
    def get_current(cls: Type[T], no_error=...) -> T:
        ...
    
    @classmethod
    def set_current(cls: Type[T], value: T): # -> None:
        ...
    


