"""
This type stub file was generated by pyright.
"""

DEFAULT_FILTER = ...
def generate_payload(exclude=..., **kwargs): # -> dict[str, Unknown]:
    """
    Generate payload

    Usage: payload = generate_payload(**locals(), exclude=['foo'])

    :param exclude:
    :param kwargs:
    :return: dict
    """
    ...

def prepare_arg(value): # -> Any | str | int:
    """
    Stringify dicts/lists and convert datetime/timedelta to unix-time

    :param value:
    :return:
    """
    ...

def prepare_file(payload, files, key, file): # -> None:
    ...

def prepare_attachment(payload, files, key, file): # -> None:
    ...

