"""
This type stub file was generated by pyright.
"""

from . import base

class BotCommand(base.TelegramObject):
    """
    This object represents a bot command.

    https://core.telegram.org/bots/api#botcommand
    """
    command: base.String = ...
    description: base.String = ...
    def __init__(self, command: base.String, description: base.String) -> None:
        ...
    


