"""
This type stub file was generated by pyright.
"""

import datetime
from . import base
from .chat import Chat
from .chat_invite_link import ChatInviteLink
from .chat_member import ChatMember
from .user import User

class ChatMemberUpdated(base.TelegramObject):
    """
    This object represents changes in the status of a chat member.

    https://core.telegram.org/bots/api#chatmemberupdated
    """
    chat: Chat = ...
    from_user: User = ...
    date: datetime.datetime = ...
    old_chat_member: ChatMember = ...
    new_chat_member: ChatMember = ...
    invite_link: ChatInviteLink = ...


