"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from . import base
from .chat import Chat
from .chat_invite_link import ChatInviteLink
from .user import User


class ChatJoinRequest(base.TelegramObject):
    """
    Represents a join request sent to a chat.

    https://core.telegram.org/bots/api#chatjoinrequest
    """
    chat: Chat = ...
    from_user: User = ...
    user_chat_id: base.Integer = ...
    date: datetime = ...
    bio: base.String = ...
    invite_link: ChatInviteLink = ...

    async def approve(self) -> base.Boolean:
        ...

    async def decline(self) -> base.Boolean:
        ...
