"""
This type stub file was generated by pyright.
"""
# flake8: noqa
from . import base, File
import io
class ChatPhoto(base.TelegramObject):
    """
    This object represents a chat photo.

    https://core.telegram.org/bots/api#chatphoto
    """
    small_file_id: base.String = ...
    small_file_unique_id: base.String = ...
    big_file_id: base.String = ...
    big_file_unique_id: base.String = ...

    async def download_small(
        self,
        destination=...,
        timeout=...,
        chunk_size=...,
        seek=...,
        make_dirs=...
    ) -> io.BytesIO | io.FileIO:
        """
        Download file

        :param destination: filename or instance of :class:`io.IOBase`. For e. g. :class:`io.BytesIO`
        :param timeout: Integer
        :param chunk_size: Integer
        :param seek: Boolean - go to start of file when downloading is finished.
        :param make_dirs: Make dirs if not exist
        :return: destination
        """
        ...

    async def download_big(self, destination=..., timeout=..., chunk_size=..., seek=..., make_dirs=...) -> io.BytesIO | io.FileIO:
        """
        Download file

        :param destination: filename or instance of :class:`io.IOBase`. For e. g. :class:`io.BytesIO`
        :param timeout: Integer
        :param chunk_size: Integer
        :param seek: Boolean - go to start of file when downloading is finished.
        :param make_dirs: Make dirs if not exist
        :return: destination
        """
        ...

    async def get_small_file(self) -> File:
        ...
    
    async def get_big_file(self) -> File:
        ...
    
    def __hash__(self) -> int:
        ...
    


