"""
This type stub file was generated by pyright.
"""

import typing
from . import base
# flake8: noqa

class ForceReply(base.TelegramObject):
    """
    Upon receiving a message with this object, Telegram clients will
    display a reply interface to the user (act as if the user has
    selected the bot's message and tapped 'Reply'). This can be
    extremely useful if you want to create user-friendly step-by-step
    interfaces without having to sacrifice privacy mode.

    https://core.telegram.org/bots/api#forcereply
    """
    force_reply: base.Boolean = ...
    input_field_placeholder: base.String = ...
    selective: base.Boolean = ...

    @classmethod
    def create(cls, input_field_placeholder: typing.Optional[base.String] = ..., selective: typing.Optional[base.Boolean] = ...) -> ForceReply:
        """
        Create new force reply

        :param selective:
        :param input_field_placeholder:
        :return:
        """
        ...
    


