"""
This type stub file was generated by pyright.
"""

from . import base
# flake8: noqa

class ForumTopicClosed(base.TelegramObject):
    """
    This object represents a service message about a forum topic closed in the chat. Currently holds no information.

    https://core.telegram.org/bots/api#forumtopicclosed
    """
    ...
