"""
This type stub file was generated by pyright.
"""

from . import base


class ForumTopicCreated(base.TelegramObject):
    """
    This object represents a service message about a new forum topic created \
        in the chat.

    https://core.telegram.org/bots/api#forumtopiccreated
    """
    name: base.String = ...
    icon_color: base.Integer = ...
    icon_custom_emoji_id: base.String = ...
