"""
This type stub file was generated by pyright.
"""

from . import base

class ForumTopic(base.TelegramObject):
    """
    This object represents a forum topic.

    https://core.telegram.org/bots/api#forumtopic
    """
    message_thread_id: base.Integer = ...
    name: base.String = ...
    icon_color: base.Integer = ...
    icon_custom_emoji_id: base.String = ...


