"""
This type stub file was generated by pyright.
"""

from . import base

class Invoice(base.TelegramObject):
    """
    This object contains basic information about an invoice.

    https://core.telegram.org/bots/api#invoice
    """
    title: base.String = ...
    description: base.String = ...
    start_parameter: base.String = ...
    currency: base.String = ...
    total_amount: base.Integer = ...


