"""
This type stub file was generated by pyright.
"""

from . import base

class LoginUrl(base.TelegramObject):
    """
    This object represents a parameter of the inline keyboard button used to automatically authorize a user.
    Serves as a great replacement for the Telegram Login Widget when the user is coming from Telegram.
    All the user needs to do is tap/click a button and confirm that they want to log in.

    https://core.telegram.org/bots/api#loginurl
    """
    url: base.String = ...
    forward_text: base.String = ...
    bot_username: base.String = ...
    request_write_access: base.Boolean = ...
    def __init__(self, url: base.String, forward_text: base.String = ..., bot_username: base.String = ..., request_write_access: base.Boolean = ..., **kwargs) -> None:
        ...
    


