"""
This type stub file was generated by pyright.
"""

from . import base

class MaskPosition(base.TelegramObject):
    """
    This object describes the position on faces where a mask should be placed by default.

    https://core.telegram.org/bots/api#maskposition
    """
    point: base.String = ...
    x_shift: base.Float = ...
    y_shift: base.Float = ...
    scale: base.Float = ...


