"""
This type stub file was generated by pyright.
"""
# flake8: noqa
import typing
from . import base
from .web_app_info import WebAppInfo
from ..utils import helper

class MenuButton(base.TelegramObject):
    """
    This object describes the bot's menu button in a private chat. It should be one of

     - MenuButtonCommands
     - MenuButtonWebApp
     - MenuButtonDefault

    If a menu button other than MenuButtonDefault is set for a private chat,
    then it is applied in the chat.
    Otherwise the default menu button is applied.
    By default, the menu button opens the list of bot commands.
    """
    type: base.String = ...
    @classmethod
    def resolve(cls, **kwargs) -> typing.Union[MenuButtonCommands, MenuButtonDefault, MenuButtonWebApp,]:
        ...
    


class MenuButtonCommands(MenuButton):
    """
    Represents a menu button, which opens the bot's list of commands.

    Source: https://core.telegram.org/bots/api#menubuttoncommands
    """
    type: base.String = ...
    def __init__(self, **kwargs) -> None:
        ...
    


class MenuButtonWebApp(MenuButton):
    """
    Represents a menu button, which launches a Web App.

    Source: https://core.telegram.org/bots/api#menubuttonwebapp
    """
    type: base.String = ...
    text: base.String = ...
    web_app: WebAppInfo = ...
    def __init__(self, text: base.String, web_app: WebAppInfo, **kwargs) -> None:
        ...
    


class MenuButtonDefault(MenuButton):
    """
    Describes that no specific value for the menu button was set.

    Source: https://core.telegram.org/bots/api#menubuttondefault
    """
    type: base.String = ...
    def __init__(self, **kwargs) -> None:
        ...
    


class MenuButtonType(helper.Helper):
    mode = ...
    DEFAULT = ...
    COMMANDS = ...
    WEB_APP = ...
