"""
This type stub file was generated by pyright.
"""

from . import base
from .shipping_address import ShippingAddress

class OrderInfo(base.TelegramObject):
    """
    This object represents information about an order.

    https://core.telegram.org/bots/api#orderinfo
    """
    name: base.String = ...
    phone_number: base.String = ...
    email: base.String = ...
    shipping_address: ShippingAddress = ...


