"""
This type stub file was generated by pyright.
"""

from . import base

class PassportFile(base.TelegramObject):
    """
    This object represents a file uploaded to Telegram Passport.
    Currently all Telegram Passport files are in JPEG format when decrypted and don't exceed 10MB.

    https://core.telegram.org/bots/api#passportfile
    """
    file_id: base.String = ...
    file_unique_id: base.String = ...
    file_size: base.Integer = ...
    file_date: base.Integer = ...


