"""
This type stub file was generated by pyright.
"""

from . import base
from .shipping_address import ShippingAddress
from .user import User

class ShippingQuery(base.TelegramObject):
    """
    This object contains information about an incoming shipping query.

    https://core.telegram.org/bots/api#shippingquery
    """
    id: base.String = ...
    from_user: User = ...
    invoice_payload: base.String = ...
    shipping_address: ShippingAddress = ...
    def __hash__(self) -> int:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    


