"""
This type stub file was generated by pyright.
"""

from . import base

class ShippingAddress(base.TelegramObject):
    """
    This object represents a shipping address.

    https://core.telegram.org/bots/api#shippingaddress
    """
    country_code: base.String = ...
    state: base.String = ...
    city: base.String = ...
    street_line1: base.String = ...
    street_line2: base.String = ...
    post_code: base.String = ...


