"""
This type stub file was generated by pyright.
"""

from . import base, mixins
from .mask_position import MaskPosition
from .photo_size import PhotoSize
from .file import File

class Sticker(base.TelegramObject, mixins.Downloadable):
    """
    This object represents a sticker.

    https://core.telegram.org/bots/api#sticker
    """
    file_id: base.String = ...
    file_unique_id: base.String = ...
    type: base.String = ...
    width: base.Integer = ...
    height: base.Integer = ...
    is_animated: base.Boolean = ...
    is_video: base.Boolean = ...
    thumb: PhotoSize = ...
    emoji: base.String = ...
    set_name: base.String = ...
    premium_animation: File = ...
    mask_position: MaskPosition = ...
    custom_emoji_id: base.String = ...
    file_size: base.Integer = ...
    async def set_position_in_set(self, position: base.Integer) -> base.Boolean:
        """
        Use this method to move a sticker in a set created by the bot to a specific position.

        Source: https://core.telegram.org/bots/api#setstickerpositioninset

        :param position: New sticker position in the set, zero-based
        :type position: :obj:`base.Integer`
        :return: Returns True on success
        :rtype: :obj:`base.Boolean`
        """
        ...
    
    async def delete_from_set(self) -> base.Boolean:
        """
        Use this method to delete a sticker from a set created by the bot.

        Source: https://core.telegram.org/bots/api#deletestickerfromset

        :return: Returns True on success
        :rtype: :obj:`base.Boolean`
        """
        ...
    


