"""
This type stub file was generated by pyright.
"""

import babel
from typing import Optional
from . import base
from ..utils.deprecated import deprecated

class User(base.TelegramObject):
    """
    This object represents a Telegram user or bot.

    https://core.telegram.org/bots/api#user
    """
    id: base.Integer = ...
    is_bot: base.Boolean = ...
    first_name: base.String = ...
    last_name: base.String = ...
    username: base.String = ...
    language_code: base.String = ...
    is_premium: base.Boolean = ...
    added_to_attachment_menu: base.Boolean = ...
    can_join_groups: base.Boolean = ...
    can_read_all_group_messages: base.Boolean = ...
    supports_inline_queries: base.Boolean = ...
    @property
    def full_name(self): # -> str | String:
        """
        You can get full name of user.

        :return: str
        """
        ...
    
    @property
    def mention(self): # -> str | String:
        """
        You can get user's username to mention him
        Full name will be returned if user has no username

        :return: str
        """
        ...
    
    @property
    def locale(self) -> Optional[babel.core.Locale]:
        """
        Get user's locale

        :return: :class:`babel.core.Locale`
        """
        ...
    
    @property
    def url(self) -> str:
        ...
    
    def get_mention(self, name: Optional[str] = ..., as_html: Optional[bool] = ...) -> str:
        ...
    
    @deprecated('`get_user_profile_photos` is outdated, please use `get_profile_photos`', stacklevel=3)
    async def get_user_profile_photos(self, offset=..., limit=...): # -> UserProfilePhotos:
        ...
    
    async def get_profile_photos(self, offset=..., limit=...): # -> UserProfilePhotos:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __int__(self) -> int:
        ...
    


