"""
This type stub file was generated by pyright.
"""

from . import base

class UserShared(base.TelegramObject):
    """
    This object contains information about the user whose identifier was
    shared with the bot using a KeyboardButtonRequestUser button.

    https://core.telegram.org/bots/api#usershared
    """
    request_id: base.Integer = ...
    user_id: base.Integer = ...


