"""
This type stub file was generated by pyright.
"""

from . import base, mixins

class VideoChatStarted(base.TelegramObject, mixins.Downloadable):
    """
    This object represents a service message about a video chat started in the chat. Currently holds no information.

    https://core.telegram.org/bots/api#videochatstarted
    """
    ...


