"""
This type stub file was generated by pyright.
"""

import typing
from . import base, mixins
from .user import User

class VideoChatParticipantsInvited(base.TelegramObject, mixins.Downloadable):
    """
    This object represents a service message about new members invited to a video chat.

    https://core.telegram.org/bots/api#videochatparticipantsinvited
    """
    users: typing.List[User] = ...


