"""
This type stub file was generated by pyright.
"""

from . import base, mixins

class VideoChatEnded(base.TelegramObject, mixins.Downloadable):
    """
    This object represents a service message about a video chat scheduled in the chat.

    https://core.telegram.org/bots/api#videochatended
    """
    duration: base.Integer = ...


