"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from . import base

class VoiceChatScheduled(base.TelegramObject):
    """
    This object represents a service message about a voice chat scheduled in the chat.

    https://core.telegram.org/bots/api#voicechatscheduled
    """
    start_date: datetime = ...


