"""
This type stub file was generated by pyright.
"""

from . import base, mixins

class Voice(base.TelegramObject, mixins.Downloadable):
    """
    This object represents a voice note.

    https://core.telegram.org/bots/api#voice
    """
    file_id: base.String = ...
    file_unique_id: base.String = ...
    duration: base.Integer = ...
    mime_type: base.String = ...
    file_size: base.Integer = ...


