"""
This type stub file was generated by pyright.
"""

from . import base, mixins

class VoiceChatEnded(base.TelegramObject, mixins.Downloadable):
    """
    This object represents a service message about a voice chat ended in the chat.

    https://core.telegram.org/bots/api#voicechatended
    """
    duration: base.Integer = ...


