"""
This type stub file was generated by pyright.
"""

from . import base

class WebAppInfo(base.TelegramObject):
    """
    Contains information about a Web App.

    Source: https://core.telegram.org/bots/api#webappinfo
    """
    url: base.String = ...


