"""
This type stub file was generated by pyright.
"""

from . import base

class WebAppData(base.TelegramObject):
    """
    Contains data sent from a Web App to the bot.

    Source: https://core.telegram.org/bots/api#webappdata
    """
    data: str = ...
    button_text: str = ...


